version: '3.7'

services:
  db-postgres:
  # su postgres && psql -d casdoor -U pg-casdoor-username
      image: qpod0dev/postgres-ext
      container_name: db-postgres
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  svc-jupyter:
      image: quay.io/jupyter/minimal-notebook
      container_name: dev-jupyter
      ports:
        - 8888:8888
      depends_on:
        - db-postgres
