version: "3"

services:
  cdw:
    image: "docker.io/qpod/greenplum"
    container_name: gpdb-cdw
    volumes:
    - greenplum-cdw:/home/gpadmin
    ports:
      - "12222:22"
      - "15432:5432"
    hostname: cdw
    tty: true
    networks:
      - greenplum

  sdw1:
    image: "docker.io/qpod/greenplum"
    container_name: gpdb-sdw1
    volumes:
    - greenplum-cdw:/home/gpadmin
    hostname: sdw1
    tty: true
    networks:
      - greenplum

  sdw2:
    image: "docker.io/qpod/greenplum"
    container_name: gpdb-sdw2
    volumes:
    - greenplum-cdw:/home/gpadmin
    hostname: sdw2
    tty: true
    networks:
      - greenplum

networks:
  greenplum:
    ipam:
      config:
      - subnet: 10.188.0.0/24
        gateway: 10.188.0.1

volumes:
 greenplum-cdw:
 greenplum-sdw1:
 greenplum-sdw2:
