name: qpod-data-lab

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  qpod_bigdata:
    name: qpod/bigdata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          source ./tool.sh
          build_image bigdata latest         docker_bigdata/Dockerfile       && push_image

  qpod_elasticsearch:
    name: qpod/elasticsearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          source ./tool.sh
          build_image elasticsearch latest   docker_elasticsearch/Dockerfile && push_image

  qpod_kafka_confluent:
    name: qpod/kafka_confluent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          source ./tool.sh
          build_image kafka latest          docker_kafka_confluent/Dockerfile && push_image

  qpod_greenplum:
    name: qpod/greenplum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          source ./tool.sh
          build_image greenplum latest      docker_greenplum/Dockerfile && push_image
